import nextConnect from 'next-connect';
import { NextApiRequest, NextApiResponse } from 'next';
import { getCookies } from 'cookies-next';
const apiRoute = nextConnect<NextApiRequest, NextApiResponse>({
  onError(error, req, res) {
    res
      .status(501)
      .json({ error: `Sorry something Happened! ${error.message}` });
  },
  onNoMatch(req, res) {
    res
      .status(405)
      .json({ success: false, Error: `Method '${req.method}' Not Allowed` });
  },
});
const galleryImages = [
  {
    src: '/img/bell/black.jpg',
    model: 'bell',
    caption_en: 'Black Bell',
    caption_th: 'แบล็คเบลล์',
  },
  {
    src: '/img/bell/blue.png',
    model: 'bell',
    caption_en: 'Blue Bell(UV Glow)',
    caption_th: 'บลูเบลล์ (เรืองแสง UV)',
  },
  {
    src: '/img/bell/blue.jpg',
    model: 'bell',
    caption_en: 'Blue Bell',
    caption_th: 'บลูเบลล์',
  },
  {
    src: '/img/bell/green.png',
    model: 'bell',
    caption_en: 'Green Bell(UV Glow)',
    caption_th: 'กรีนเบลล์ (เรืองแสง UV)',
  },
  {
    src: '/img/bell/green.jpg',
    model: 'bell',
    caption_en: 'Green Bell',
    caption_th: 'กรีนเบลล์ ',
  },
  {
    src: '/img/bell/magneta.png',
    model: 'bell',
    caption_en: 'Magenta Bell(UV Glow)',
    caption_th: 'ระฆังสีม่วงแดง (เรืองแสงยูวี)',
  },
  {
    src: '/img/bell/magenta.jpg',
    model: 'bell',
    caption_en: 'Magenta Bell',
    caption_th: 'ระฆังสีม่วงแดง ',
  },
  {
    src: '/img/bell/orange.png',
    model: 'bell',
    caption_en: 'Orange Bell(UV Glow)',
    caption_th: 'ออเรนจ์เบลล์ (เรืองแสง UV) ',
  },
  {
    src: '/img/bell/orange.jpg',
    model: 'bell',
    caption_en: 'Orange Bell',
    caption_th: 'ออเรนจ์เบลล์ ',
  },
  {
    src: '/img/bell/pink.png',
    model: 'bell',
    caption_en: 'Pink Bell (UV Glow)',
    caption_th: 'พิงค์เบลล์ (ยูวีโกลว์) ',
  },
  {
    src: '/img/bell/pink.jpg',
    model: 'bell',
    caption_en: 'Pink Bell',
    caption_th: 'พิงค์เบลล์ ',
  },
  {
    src: '/img/bell/red.png',
    model: 'bell',
    caption_en: 'Red Bell (UV Glow)',
    caption_th: 'ระฆังแดง (เรืองแสง UV)',
  },
  {
    src: '/img/bell/red.jpg',
    model: 'bell',
    caption_en: 'Red Bell',
    caption_th: 'ระฆังแดง ',
  },
  {
    src: '/img/bell/violet.png',
    model: 'bell',
    caption_en: 'Violet Bell (UV Glow)',
    caption_th: 'ไวโอเล็ตเบลล์ (เรืองแสง UV)',
  },
  {
    src: '/img/bell/violet.jpg',
    model: 'bell',
    caption_en: 'Violet Bell',
    caption_th: 'ไวโอเล็ตเบลล์',
  },
  {
    src: '/img/bell/white.png',
    model: 'bell',
    caption_en: 'White Bell (UV Glow)',
    caption_th: 'สีขาวเบลล์ (ยูวี โกลว์)',
  },
  {
    src: '/img/bell/white.jpg',
    model: 'bell',
    caption_en: 'White Bell',
    caption_th: 'สีขาวเบลล์ ',
  },
  {
    src: '/img/bell/yellow.png',
    model: 'bell',
    caption_en: 'Yellow Bell (UV Glow)',
    caption_th: 'ระฆังสีเหลือง (เรืองแสง UV)',
  },
  {
    src: '/img/bell/yellow.jpg',
    model: 'bell',
    caption_en: 'Yellow Bell',
    caption_th: 'ระฆังสีเหลือง',
  },
  {
    src: '/img/bell/yellowOrange.png',
    model: 'bell',
    caption_en: 'Yellow Orange Bell (UV Glow)',
    caption_th: 'สีเหลืองส้มกระดิ่ง (เรืองแสง UV)',
  },
  {
    src: '/img/bell/yellowOrange.jpg',
    model: 'bell',
    caption_en: 'Yellow Orange Bell',
    caption_th: 'สีเหลืองส้มกระดิ่ง ',
  },

  {
    src: '/img/crookedTriangle/black.jpg',
    model: 'crookedTriangle',
    caption_en: 'Black Crooked Triangle',
    caption_th: 'สามเหลี่ยมคดเคี้ยวสีดำ',
  },
  {
    src: '/img/crookedTriangle/blue.png',
    model: 'crookedTriangle',
    caption_en: 'Blue Crooked Triangle(UV Glow)',
    caption_th: 'สามเหลี่ยมคดเคี้ยวสีน้ำเงิน (เรืองแสง UV)',
  },
  {
    src: '/img/crookedTriangle/blue.jpg',
    model: 'crookedTriangle',
    caption_en: 'Blue Crooked Triangle',
    caption_th: 'สามเหลี่ยมคดเคี้ยวสีน้ำเงิน',
  },
  {
    src: '/img/crookedTriangle/green.png',
    model: 'crookedTriangle',
    caption_en: 'Green Crooked Triangle(UV Glow)',
    caption_th: 'สามเหลี่ยมคดเคี้ยวสีเขียว (เรืองแสง UV)',
  },
  {
    src: '/img/crookedTriangle/green.jpg',
    model: 'crookedTriangle',
    caption_en: 'Green Crooked Triangle',
    caption_th: 'สามเหลี่ยมคดเคี้ยวสีเขียว',
  },
  {
    src: '/img/crookedTriangle/magneta.png',
    model: 'crookedTriangle',
    caption_en: 'Magenta Crooked Triangle(UV Glow)',
    caption_th: 'สามเหลี่ยมคดเคี้ยวสีม่วงแดง (เรืองแสงยูวี)',
  },
  {
    src: '/img/crookedTriangle/magenta.jpg',
    model: 'crookedTriangle',
    caption_en: 'Magenta Crooked Triangle',
    caption_th: 'สามเหลี่ยมคดเคี้ยวสีม่วงแดง ',
  },
  {
    src: '/img/crookedTriangle/orange.png',
    model: 'crookedTriangle',
    caption_en: 'Orange Crooked Triangle(UV Glow)',
    caption_th: 'สามเหลี่ยมมุมส้ม (เรืองแสง UV)',
  },
  {
    src: '/img/crookedTriangle/orange.jpg',
    model: 'crookedTriangle',
    caption_en: 'Orange Crooked Triangle',
    caption_th: 'สามเหลี่ยมมุมส้ม ',
  },
  {
    src: '/img/crookedTriangle/pink.png',
    model: 'crookedTriangle',
    caption_en: 'Pink Crooked Triangle (UV Glow)',
    caption_th: 'สามเหลี่ยมคดเคี้ยวสีชมพู (เรืองแสง UV)',
  },
  {
    src: '/img/crookedTriangle/pink.jpg',
    model: 'crookedTriangle',
    caption_en: 'Pink Crooked Triangle',
    caption_th: 'สามเหลี่ยมคดเคี้ยวสีชมพู  ',
  },
  {
    src: '/img/crookedTriangle/red.png',
    model: 'crookedTriangle',
    caption_en: 'Red Crooked Triangle (UV Glow)',
    caption_th: 'สามเหลี่ยมมุมฉากสีแดง (เรืองแสง UV)',
  },
  {
    src: '/img/crookedTriangle/red.jpg',
    model: 'crookedTriangle',
    caption_en: 'Red Crooked Triangle',
    caption_th: 'สามเหลี่ยมมุมฉากสีแดง  ',
  },
  {
    src: '/img/crookedTriangle/violet.png',
    model: 'crookedTriangle',
    caption_en: 'Violet Crooked Triangle (UV Glow)',
    caption_th: 'สามเหลี่ยมคดเคี้ยวสีม่วง (เรืองแสง UV)',
  },
  {
    src: '/img/crookedTriangle/violet.jpg',
    model: 'crookedTriangle',
    caption_en: 'Violet Crooked Triangle',
    caption_th: 'สามเหลี่ยมคดเคี้ยวสีม่วง ',
  },
  {
    src: '/img/crookedTriangle/white.png',
    model: 'crookedTriangle',
    caption_en: 'White Crooked Triangle (UV Glow)',
    caption_th: 'สามเหลี่ยมคดเคี้ยวสีขาว (เรืองแสง UV)',
  },
  {
    src: '/img/crookedTriangle/white.jpg',
    model: 'crookedTriangle',
    caption_en: 'White Crooked Triangle',
    caption_th: 'สามเหลี่ยมคดเคี้ยวสีขาว  ',
  },
  {
    src: '/img/crookedTriangle/yellow.png',
    model: 'crookedTriangle',
    caption_en: 'Yellow Crooked Triangle (UV Glow)',
    caption_th: 'สามเหลี่ยมคดเคี้ยวสีเหลือง (เรืองแสง UV)',
  },
  {
    src: '/img/crookedTriangle/yellow.jpg',
    model: 'crookedTriangle',
    caption_en: 'Yellow Crooked Triangle',
    caption_th: 'สามเหลี่ยมคดเคี้ยวสีเหลือง ',
  },
  {
    src: '/img/crookedTriangle/yellowOrange.png',
    model: 'crookedTriangle',
    caption_en: 'Yellow Orange Crooked Triangle (UV Glow)',
    caption_th: 'สามเหลี่ยมมุมฉากสีเหลืองส้ม (เรืองแสง UV)',
  },
  {
    src: '/img/crookedTriangle/yellowOrange.jpg',
    model: 'crookedTriangle',
    caption_en: 'Yellow Orange Crooked Triangle',
    caption_th: 'สามเหลี่ยมมุมฉากสีเหลืองส้ม  ',
  },

  {
    src: '/img/diamond/black.jpg',
    model: 'diamond',
    caption_en: 'Black Diamond',
    caption_th: 'เพชรดำ',
  },
  {
    src: '/img/diamond/blue.png',
    model: 'diamond',
    caption_en: 'Blue Diamond(UV Glow)',
    caption_th: 'บลูไดมอนด์ (เรืองแสง UV))',
  },
  {
    src: '/img/diamond/blue.jpg',
    model: 'diamond',
    caption_en: 'Blue Diamond',
    caption_th: 'บลูไดมอนด์ ',
  },
  {
    src: '/img/diamond/green.png',
    model: 'diamond',
    caption_en: 'Green Diamond(UV Glow)',
    caption_th: 'เพชรสีเขียว (เรืองแสง UV)',
  },
  {
    src: '/img/diamond/green.jpg',
    model: 'diamond',
    caption_en: 'Green Diamond',
    caption_th: 'เพชรสีเขียว ',
  },
  {
    src: '/img/diamond/magneta.png',
    model: 'diamond',
    caption_en: 'Magenta Diamond(UV Glow)',
    caption_th: 'เพชรสีม่วงแดง (เรืองแสงยูวี)',
  },
  {
    src: '/img/diamond/magneta.jpg',
    model: 'diamond',
    caption_en: 'Magenta Diamond',
    caption_th: 'เพชรสีม่วงแดง ',
  },
  {
    src: '/img/diamond/orange.png',
    model: 'diamond',
    caption_en: 'Orange Diamond(UV Glow)',
    caption_th: 'เพชรสีส้ม (เรืองแสง UV)',
  },
  {
    src: '/img/diamond/orange.jpg',
    model: 'diamond',
    caption_en: 'Orange Diamond',
    caption_th: 'เพชรสีส้ม  ',
  },
  {
    src: '/img/diamond/pink.png',
    model: 'diamond',
    caption_en: 'Pink Diamond (UV Glow)',
    caption_th: 'เพชรสีชมพู (เรืองแสง UV)',
  },
  {
    src: '/img/diamond/pink.jpg',
    model: 'diamond',
    caption_en: 'Pink Diamond',
    caption_th: 'เพชรสีชมพู',
  },
  {
    src: '/img/diamond/red.png',
    model: 'diamond',
    caption_en: 'Red Diamond (UV Glow)',
    caption_th: 'เพชรสีแดง (เรืองแสง UV)',
  },
  {
    src: '/img/diamond/red.jpg',
    model: 'diamond',
    caption_en: 'Red Diamond',
    caption_th: 'เพชรสีแดง',
  },
  {
    src: '/img/diamond/violet.png',
    model: 'diamond',
    caption_en: 'Violet Diamond (UV Glow)',
    caption_th: 'เพชรสีม่วง (เรืองแสง UV)',
  },
  {
    src: '/img/diamond/violet.jpg',
    model: 'diamond',
    caption_en: 'Violet Diamond',
    caption_th: 'เพชรสีม่วง ',
  },
  {
    src: '/img/diamond/white.png',
    model: 'diamond',
    caption_en: 'White Diamond (UV Glow)',
    caption_th: 'เพชรขาว (เรืองแสง UV)',
  },
  {
    src: '/img/diamond/white.jpg',
    model: 'diamond',
    caption_en: 'White Diamond',
    caption_th: 'เพชรขาว  ',
  },
  {
    src: '/img/diamond/yellow.png',
    model: 'diamond',
    caption_en: 'Yellow Diamond (UV Glow)',
    caption_th: 'เพชรสีเหลือง (เรืองแสง UV)',
  },
  {
    src: '/img/diamond/yellow.jpg',
    model: 'diamond',
    caption_en: 'Yellow Diamond',
    caption_th: 'เพชรสีเหลือง ',
  },
  {
    src: '/img/diamond/yellowOrange.png',
    model: 'diamond',
    caption_en: 'Yellow Orange Diamond (UV Glow)',
    caption_th: 'เพชรสีส้มเหลือง (เรืองแสง UV)',
  },
  {
    src: '/img/diamond/yellowOrange.jpg',
    model: 'diamond',
    caption_en: 'Yellow Orange Diamond',
    caption_th: 'เพชรสีส้มเหลือง  ',
  },
  {
    src: '/img/longTriangle/black.jpg',
    model: 'longTriangle',
    caption_en: 'Black Long Triangle',
    caption_th: 'สามเหลี่ยมยาวสีดำ',
  },
  {
    src: '/img/longTriangle/blue.png',
    model: 'longTriangle',
    caption_en: 'Blue Long Triangle(UV Glow)',
    caption_th: 'บลูไดมอนด์ (เรืองแสง UV))',
  },
  {
    src: '/img/longTriangle/blue.jpg',
    model: 'longTriangle',
    caption_en: 'Blue Long Triangle',
    caption_th: 'บลูไดมอนด์ ',
  },
  {
    src: '/img/longTriangle/green.png',
    model: 'longTriangle',
    caption_en: 'Green Long Triangle(UV Glow)',
    caption_th: 'สามเหลี่ยมยาวสีเขียว (เรืองแสง UV)',
  },
  {
    src: '/img/longTriangle/green.jpg',
    model: 'longTriangle',
    caption_en: 'Green Long Triangle',
    caption_th: 'สามเหลี่ยมยาวสีเขียว ',
  },
  {
    src: '/img/longTriangle/magneta.png',
    model: 'longTriangle',
    caption_en: 'Magenta Long Triangle(UV Glow)',
    caption_th: 'สามเหลี่ยมยาวสีม่วงแดง (เรืองแสงยูวี)',
  },
  {
    src: '/img/longTriangle/magneta.jpg',
    model: 'longTriangle',
    caption_en: 'Magenta Long Triangle',
    caption_th: 'สามเหลี่ยมยาวสีม่วงแดง ',
  },
  {
    src: '/img/longTriangle/orange.png',
    model: 'longTriangle',
    caption_en: 'Orange Long Triangle(UV Glow)',
    caption_th: 'สามเหลี่ยมยาวสีส้ม (เรืองแสง UV)',
  },
  {
    src: '/img/longTriangle/orange.jpg',
    model: 'longTriangle',
    caption_en: 'Orange Long Triangle',
    caption_th: 'สามเหลี่ยมยาวสีส้ม  ',
  },
  {
    src: '/img/longTriangle/pink.png',
    model: 'longTriangle',
    caption_en: 'Pink Long Triangle (UV Glow)',
    caption_th: 'สามเหลี่ยมยาวสีชมพู (เรืองแสง UV)',
  },
  {
    src: '/img/longTriangle/pink.jpg',
    model: 'longTriangle',
    caption_en: 'Pink Long Triangle',
    caption_th: 'สามเหลี่ยมยาวสีชมพู',
  },
  {
    src: '/img/longTriangle/red.png',
    model: 'longTriangle',
    caption_en: 'Red Long Triangle (UV Glow)',
    caption_th: 'สามเหลี่ยมยาวสีแดง (เรืองแสง UV)',
  },
  {
    src: '/img/longTriangle/red.jpg',
    model: 'longTriangle',
    caption_en: 'Red Long Triangle',
    caption_th: 'สามเหลี่ยมยาวสีแดง',
  },
  {
    src: '/img/longTriangle/violet.png',
    model: 'longTriangle',
    caption_en: 'Violet Long Triangle (UV Glow)',
    caption_th: 'สามเหลี่ยมยาวสีม่วง (เรืองแสง UV)',
  },
  {
    src: '/img/longTriangle/violet.jpg',
    model: 'longTriangle',
    caption_en: 'Violet Long Triangle',
    caption_th: 'สามเหลี่ยมยาวสีม่วง ',
  },
  {
    src: '/img/longTriangle/white.png',
    model: 'longTriangle',
    caption_en: 'White Long Triangle (UV Glow)',
    caption_th: 'สามเหลี่ยมยาวสีขาว (เรืองแสง UV)',
  },
  {
    src: '/img/longTriangle/white.jpg',
    model: 'longTriangle',
    caption_en: 'White Long Triangle',
    caption_th: 'สามเหลี่ยมยาวสีขาว  ',
  },
  {
    src: '/img/longTriangle/yellow.png',
    model: 'longTriangle',
    caption_en: 'Yellow Long Triangle (UV Glow)',
    caption_th: 'สามเหลี่ยมยาวสีเหลือง (เรืองแสง UV)',
  },
  {
    src: '/img/longTriangle/yellow.jpg',
    model: 'longTriangle',
    caption_en: 'Yellow Long Triangle',
    caption_th: 'สามเหลี่ยมยาวสีเหลือง ',
  },
  {
    src: '/img/longTriangle/yellowOrange.png',
    model: 'longTriangle',
    caption_en: 'Yellow Orange Long Triangle (UV Glow)',
    caption_th: 'สามเหลี่ยมยาวสีเหลืองส้ม (เรืองแสง UV)',
  },
  {
    src: '/img/longTriangle/yellowOrange.jpg',
    model: 'longTriangle',
    caption_en: 'Yellow Orange Long Triangle',
    caption_th: 'สามเหลี่ยมยาวสีเหลืองส้ม  ',
  },
  {
    src: '/img/octagon/black.jpg',
    model: 'octagon',
    caption_en: 'Black Octagon',
    caption_th: 'แปดเหลี่ยมดำ',
  },
  {
    src: '/img/octagon/blue.png',
    model: 'octagon',
    caption_en: 'Blue Octagon(UV Glow)',
    caption_th: 'แปดเหลี่ยมสีน้ำเงิน (เรืองแสง UV))',
  },
  {
    src: '/img/octagon/blue.jpg',
    model: 'octagon',
    caption_en: 'Blue Octagon',
    caption_th: 'แปดเหลี่ยมสีน้ำเงิน ',
  },
  {
    src: '/img/octagon/green.png',
    model: 'octagon',
    caption_en: 'Green Octagon(UV Glow)',
    caption_th: 'แปดเหลี่ยมเขียว (เรืองแสง UV)',
  },
  {
    src: '/img/octagon/green.jpg',
    model: 'octagon',
    caption_en: 'Green Octagon',
    caption_th: 'แปดเหลี่ยมเขียว ',
  },
  {
    src: '/img/octagon/magneta.png',
    model: 'octagon',
    caption_en: 'Magenta Octagon(UV Glow)',
    caption_th: 'สีม่วงแดงแปดเหลี่ยม (เรืองแสงยูวี)',
  },
  {
    src: '/img/octagon/magneta.jpg',
    model: 'octagon',
    caption_en: 'Magenta Octagon',
    caption_th: 'สีม่วงแดงแปดเหลี่ยม ',
  },
  {
    src: '/img/octagon/orange.png',
    model: 'octagon',
    caption_en: 'Orange Octagon(UV Glow)',
    caption_th: 'แปดเหลี่ยมสีส้ม (เรืองแสง UV)',
  },
  {
    src: '/img/octagon/orange.jpg',
    model: 'octagon',
    caption_en: 'Orange Octagon',
    caption_th: 'แปดเหลี่ยมสีส้ม  ',
  },
  {
    src: '/img/octagon/pink.png',
    model: 'octagon',
    caption_en: 'Pink Octagon (UV Glow)',
    caption_th: 'แปดเหลี่ยมสีชมพู (เรืองแสง UV)',
  },
  {
    src: '/img/octagon/pink.jpg',
    model: 'octagon',
    caption_en: 'Pink Octagon',
    caption_th: 'แปดเหลี่ยมสีชมพู',
  },
  {
    src: '/img/octagon/red.png',
    model: 'octagon',
    caption_en: 'Red Octagon (UV Glow)',
    caption_th: 'แปดเหลี่ยมสีแดง (เรืองแสง UV)',
  },
  {
    src: '/img/octagon/red.jpg',
    model: 'octagon',
    caption_en: 'Red Octagon',
    caption_th: 'แปดเหลี่ยมสีแดง',
  },
  {
    src: '/img/octagon/violet.png',
    model: 'octagon',
    caption_en: 'Violet Octagon (UV Glow)',
    caption_th: 'แปดเหลี่ยมสีม่วง (เรืองแสง UV)',
  },
  {
    src: '/img/octagon/violet.jpg',
    model: 'octagon',
    caption_en: 'Violet Octagon',
    caption_th: 'แปดเหลี่ยมสีม่วง ',
  },
  // {
  //   src: '/img/octagon/white.png',
  //   model: 'octagon',
  //   caption_en: 'White Octagon (UV Glow)',
  //   caption_th: 'แปดเหลี่ยมสีขาว (เรืองแสง UV)',
  // },
  // {
  //   src: '/img/octagon/white.jpg',
  //   model: 'octagon',
  //   caption_en: 'White Octagon',
  //   caption_th: 'แปดเหลี่ยมสีขาว  ',
  // },
  {
    src: '/img/octagon/yellow.png',
    model: 'octagon',
    caption_en: 'Yellow Octagon (UV Glow)',
    caption_th: 'แปดเหลี่ยมสีเหลือง (เรืองแสง UV)',
  },
  {
    src: '/img/octagon/yellow.jpg',
    model: 'octagon',
    caption_en: 'Yellow Octagon',
    caption_th: 'แปดเหลี่ยมสีเหลือง ',
  },
  {
    src: '/img/octagon/yellowOrange.png',
    model: 'octagon',
    caption_en: 'Yellow Orange Octagon (UV Glow)',
    caption_th: 'สีเหลืองส้มแปดเหลี่ยม (เรืองแสง UV)',
  },
  {
    src: '/img/octagon/yellowOrange.jpg',
    model: 'octagon',
    caption_en: 'Yellow Orange Octagon',
    caption_th: 'สีเหลืองส้มแปดเหลี่ยม  ',
  },

  {
    src: '/img/oval/black.jpg',
    model: 'oval',
    caption_en: 'Black Oval',
    caption_th: 'วงรีสีดำ',
  },
  {
    src: '/img/oval/blue.png',
    model: 'oval',
    caption_en: 'Blue Oval(UV Glow)',
    caption_th: 'วงรีสีน้ำเงิน (เรืองแสง UV))',
  },
  {
    src: '/img/oval/blue.jpg',
    model: 'oval',
    caption_en: 'Blue Oval',
    caption_th: 'วงรีสีน้ำเงิน ',
  },
  {
    src: '/img/oval/green.png',
    model: 'oval',
    caption_en: 'Green Oval(UV Glow)',
    caption_th: 'วงรีสีเขียว (เรืองแสง UV)',
  },
  {
    src: '/img/oval/green.jpg',
    model: 'oval',
    caption_en: 'Green Oval',
    caption_th: 'วงรีสีเขียว ',
  },
  {
    src: '/img/oval/magneta.png',
    model: 'oval',
    caption_en: 'Magenta Oval(UV Glow)',
    caption_th: 'วงรีสีม่วงแดง (เรืองแสงยูวี)',
  },
  {
    src: '/img/oval/magneta.jpg',
    model: 'oval',
    caption_en: 'Magenta Oval',
    caption_th: 'วงรีสีม่วงแดง ',
  },
  {
    src: '/img/oval/orange.png',
    model: 'oval',
    caption_en: 'Orange Oval(UV Glow)',
    caption_th: 'วงรีสีส้ม (เรืองแสง UV)',
  },
  {
    src: '/img/oval/orange.jpg',
    model: 'oval',
    caption_en: 'Orange Oval',
    caption_th: 'วงรีสีส้ม  ',
  },
  {
    src: '/img/oval/pink.png',
    model: 'oval',
    caption_en: 'Pink Oval (UV Glow)',
    caption_th: 'วงรีสีส้ม (เรืองแสง UV)',
  },
  {
    src: '/img/oval/pink.jpg',
    model: 'oval',
    caption_en: 'Pink Oval',
    caption_th: 'วงรีสีส้ม',
  },
  {
    src: '/img/oval/red.png',
    model: 'oval',
    caption_en: 'Red Oval (UV Glow)',
    caption_th: 'วงรีสีแดง (เรืองแสง UV)',
  },
  {
    src: '/img/oval/red.jpg',
    model: 'oval',
    caption_en: 'Red Oval',
    caption_th: 'วงรีสีแดง',
  },
  {
    src: '/img/oval/violet.png',
    model: 'oval',
    caption_en: 'Violet Oval (UV Glow)',
    caption_th: 'วงรีไวโอเล็ต (เรืองแสง UV)',
  },
  {
    src: '/img/oval/violet.jpg',
    model: 'oval',
    caption_en: 'Violet Oval',
    caption_th: 'วงรีไวโอเล็ต ',
  },
  {
    src: '/img/oval/white.png',
    model: 'oval',
    caption_en: 'White Oval (UV Glow)',
    caption_th: 'วงรีสีขาว (เรืองแสง UV)',
  },
  {
    src: '/img/oval/white.jpg',
    model: 'oval',
    caption_en: 'White Oval',
    caption_th: 'วงรีสีขาว  ',
  },
  {
    src: '/img/oval/yellow.png',
    model: 'oval',
    caption_en: 'Yellow Oval (UV Glow)',
    caption_th: 'วงรีสีเหลือง (เรืองแสง UV)',
  },
  {
    src: '/img/oval/yellow.jpg',
    model: 'oval',
    caption_en: 'Yellow Oval',
    caption_th: 'วงรีสีเหลือง ',
  },
  {
    src: '/img/oval/yellowOrange.png',
    model: 'oval',
    caption_en: 'Yellow Orange Oval (UV Glow)',
    caption_th: 'วงรีสีเหลืองส้ม (เรืองแสง UV)',
  },
  {
    src: '/img/oval/yellowOrange.jpg',
    model: 'oval',
    caption_en: 'Yellow Orange Oval',
    caption_th: 'วงรีสีเหลืองส้ม  ',
  },

  {
    src: '/img/socks/black.jpg',
    model: 'socks',
    caption_en: 'Black Socks',
    caption_th: 'ถุงเท้าสีดำ',
  },
  {
    src: '/img/socks/blue.png',
    model: 'socks',
    caption_en: 'Blue Socks(UV Glow)',
    caption_th: 'ถุงเท้าสีน้ำเงิน (เรืองแสง UV))',
  },
  {
    src: '/img/socks/blue.jpg',
    model: 'socks',
    caption_en: 'Blue Socks',
    caption_th: 'ถุงเท้าสีน้ำเงิน ',
  },
  {
    src: '/img/socks/green.png',
    model: 'socks',
    caption_en: 'Green Socks(UV Glow)',
    caption_th: 'ถุงเท้าสีเขียว (เรืองแสง UV)',
  },
  {
    src: '/img/socks/green.jpg',
    model: 'socks',
    caption_en: 'Green Socks',
    caption_th: 'ถุงเท้าสีเขียว ',
  },
  {
    src: '/img/socks/magneta.png',
    model: 'socks',
    caption_en: 'Magenta Socks(UV Glow)',
    caption_th: 'ถุงเท้าสีม่วงแดง (เรืองแสงยูวี)',
  },
  {
    src: '/img/socks/magneta.jpg',
    model: 'socks',
    caption_en: 'Magenta Socks',
    caption_th: 'ถุงเท้าสีม่วงแดง ',
  },
  {
    src: '/img/socks/orange.png',
    model: 'socks',
    caption_en: 'Orange Socks(UV Glow)',
    caption_th: 'ถุงเท้าสีส้ม (เรืองแสง UV)',
  },
  {
    src: '/img/socks/orange.jpg',
    model: 'socks',
    caption_en: 'Orange Socks',
    caption_th: 'ถุงเท้าสีส้ม  ',
  },
  {
    src: '/img/socks/pink.png',
    model: 'socks',
    caption_en: 'Pink Socks (UV Glow)',
    caption_th: 'ถุงเท้าสีชมพู (เรืองแสง UV)',
  },
  {
    src: '/img/socks/pink.jpg',
    model: 'socks',
    caption_en: 'Pink Socks',
    caption_th: 'ถุงเท้าสีชมพู',
  },
  {
    src: '/img/socks/red.png',
    model: 'socks',
    caption_en: 'Red Socks (UV Glow)',
    caption_th: 'ถุงเท้าแดง (เรืองแสง UV)',
  },
  {
    src: '/img/socks/red.jpg',
    model: 'socks',
    caption_en: 'Red Socks',
    caption_th: 'ถุงเท้าแดง',
  },
  {
    src: '/img/socks/violet.png',
    model: 'socks',
    caption_en: 'Violet Socks (UV Glow)',
    caption_th: 'ถุงเท้าสีม่วง (เรืองแสง UV)',
  },
  {
    src: '/img/socks/violet.jpg',
    model: 'socks',
    caption_en: 'Violet Socks',
    caption_th: 'ถุงเท้าสีม่วง ',
  },
  {
    src: '/img/socks/white.png',
    model: 'socks',
    caption_en: 'White Socks (UV Glow)',
    caption_th: 'ถุงเท้าสีขาว (เรืองแสง UV)',
  },
  {
    src: '/img/socks/white.jpg',
    model: 'socks',
    caption_en: 'White Socks',
    caption_th: 'ถุงเท้าสีขาว  ',
  },
  {
    src: '/img/socks/yellow.png',
    model: 'socks',
    caption_en: 'Yellow Socks (UV Glow)',
    caption_th: 'ถุงเท้าเหลือง (เรืองแสง UV)',
  },
  {
    src: '/img/socks/yellow.jpg',
    model: 'socks',
    caption_en: 'Yellow Socks',
    caption_th: 'ถุงเท้าเหลือง ',
  },
  {
    src: '/img/socks/yellowOrange.png',
    model: 'socks',
    caption_en: 'Yellow Orange Socks (UV Glow)',
    caption_th: 'ถุงเท้าเหลืองส้ม (เรืองแสง UV)',
  },
  {
    src: '/img/socks/yellowOrange.jpg',
    model: 'socks',
    caption_en: 'Yellow Orange Socks',
    caption_th: 'ถุงเท้าเหลืองส้ม  ',
  },

  {
    src: '/img/square/black.jpg',
    model: 'square',
    caption_en: 'Black Square',
    caption_th: 'แบล็คสแควร์',
  },
  {
    src: '/img/square/blue.png',
    model: 'square',
    caption_en: 'Blue Square(UV Glow)',
    caption_th: 'บลูสแควร์ (เรืองแสง UV))',
  },
  {
    src: '/img/square/blue.jpg',
    model: 'square',
    caption_en: 'Blue Square',
    caption_th: 'บลูสแควร์ ',
  },
  {
    src: '/img/square/green.png',
    model: 'square',
    caption_en: 'Green Square(UV Glow)',
    caption_th: 'กรีนสแควร์ (เรืองแสง UV)',
  },
  {
    src: '/img/square/green.jpg',
    model: 'square',
    caption_en: 'Green Square',
    caption_th: 'กรีนสแควร์ ',
  },
  {
    src: '/img/square/magneta.png',
    model: 'square',
    caption_en: 'Magenta Square(UV Glow)',
    caption_th: 'จัตุรัสม่วงแดง (เรืองแสงยูวี)',
  },
  {
    src: '/img/square/magneta.jpg',
    model: 'square',
    caption_en: 'Magenta Square',
    caption_th: 'จัตุรัสม่วงแดง ',
  },
  {
    src: '/img/square/orange.png',
    model: 'square',
    caption_en: 'Orange Square(UV Glow)',
    caption_th: 'จัตุรัสส้ม (เรืองแสง UV)',
  },
  {
    src: '/img/square/orange.jpg',
    model: 'square',
    caption_en: 'Orange Square',
    caption_th: 'จัตุรัสส้ม  ',
  },
  {
    src: '/img/square/pink.png',
    model: 'square',
    caption_en: 'Pink Square (UV Glow)',
    caption_th: 'จัตุรัสสีชมพู (เรืองแสง UV)',
  },
  {
    src: '/img/square/pink.jpg',
    model: 'square',
    caption_en: 'Pink Square',
    caption_th: 'จัตุรัสสีชมพู',
  },
  {
    src: '/img/square/red.png',
    model: 'square',
    caption_en: 'Red Square (UV Glow)',
    caption_th: 'จัตุรัสแดง (เรืองแสง UV)',
  },
  {
    src: '/img/square/red.jpg',
    model: 'square',
    caption_en: 'Red Square',
    caption_th: 'จัตุรัสแดง',
  },
  {
    src: '/img/square/white.png',
    model: 'square',
    caption_en: 'White Square (UV Glow)',
    caption_th: 'ไวท์สแควร์ (เรืองแสง UV)',
  },
  {
    src: '/img/square/white.jpg',
    model: 'square',
    caption_en: 'White Square',
    caption_th: 'ไวท์สแควร์  ',
  },
  {
    src: '/img/square/yellow.png',
    model: 'square',
    caption_en: 'Yellow Square (UV Glow)',
    caption_th: 'จัตุรัสเหลือง (เรืองแสง UV)',
  },
  {
    src: '/img/square/yellow.jpg',
    model: 'square',
    caption_en: 'Yellow Square',
    caption_th: 'จัตุรัสเหลือง ',
  },
  {
    src: '/img/square/yellowOrange.png',
    model: 'square',
    caption_en: 'Yellow Orange Square (UV Glow)',
    caption_th: 'สี่เหลี่ยมสีเหลืองส้ม (เรืองแสง UV)',
  },
  {
    src: '/img/square/yellowOrange.jpg',
    model: 'square',
    caption_en: 'Yellow Orange Square',
    caption_th: 'สี่เหลี่ยมสีเหลืองส้ม  ',
  },

  {
    src: '/img/squareWithHole/black.jpg',
    model: 'squareWithHole',
    caption_en: 'Black Square with a hole',
    caption_th: 'สี่เหลี่ยมสีดำที่มีรู',
  },
  {
    src: '/img/squareWithHole/blue.png',
    model: 'squareWithHole',
    caption_en: 'Blue Square with a hole(UV Glow)',
    caption_th: 'บลูสแควร์ที่มีรู (เรืองแสง UV))',
  },
  {
    src: '/img/squareWithHole/blue.jpg',
    model: 'squareWithHole',
    caption_en: 'Blue Square with a hole',
    caption_th: 'บลูสแควร์ที่มีรู ',
  },
  {
    src: '/img/squareWithHole/green.png',
    model: 'squareWithHole',
    caption_en: 'Green Square with a hole(UV Glow)',
    caption_th: 'กรีนสแควร์ที่มีรู (เรืองแสง UV)',
  },
  {
    src: '/img/squareWithHole/green.jpg',
    model: 'squareWithHole',
    caption_en: 'Green Square with a hole',
    caption_th: 'กรีนสแควร์ที่มีรู ',
  },
  {
    src: '/img/squareWithHole/magneta.png',
    model: 'squareWithHole',
    caption_en: 'Magenta Square with a hole(UV Glow)',
    caption_th: 'สีม่วงแดง สี่เหลี่ยมมีรู(เรืองแสงยูวี)',
  },
  {
    src: '/img/squareWithHole/magneta.jpg',
    model: 'squareWithHole',
    caption_en: 'Magenta Square with a hole',
    caption_th: 'สีม่วงแดง สี่เหลี่ยมมีรู',
  },
  {
    src: '/img/squareWithHole/orange.png',
    model: 'squareWithHole',
    caption_en: 'Orange Square with a hole(UV Glow)',
    caption_th: 'สี่เหลี่ยมสีส้มที่มีรู (เรืองแสง UV)',
  },
  {
    src: '/img/squareWithHole/orange.jpg',
    model: 'squareWithHole',
    caption_en: 'Orange Square with a hole',
    caption_th: 'สี่เหลี่ยมสีส้มที่มีรู  ',
  },
  {
    src: '/img/squareWithHole/pink.png',
    model: 'squareWithHole',
    caption_en: 'Pink Square with a hole (UV Glow)',
    caption_th: 'สี่เหลี่ยมสีชมพูที่มีรู (เรืองแสง UV)',
  },
  {
    src: '/img/squareWithHole/pink.jpg',
    model: 'squareWithHole',
    caption_en: 'Pink Square with a hole',
    caption_th: 'สี่เหลี่ยมสีชมพูที่มีรู',
  },
  {
    src: '/img/squareWithHole/red.png',
    model: 'squareWithHole',
    caption_en: 'Red Square with a hole (UV Glow)',
    caption_th: 'จัตุรัสแดงที่มีรู (เรืองแสง UV)',
  },
  {
    src: '/img/squareWithHole/red.jpg',
    model: 'squareWithHole',
    caption_en: 'Red Square with a hole',
    caption_th: 'จัตุรัสแดงที่มีรู',
  },
  {
    src: '/img/squareWithHole/white.png',
    model: 'squareWithHole',
    caption_en: 'White Square with a hole (UV Glow)',
    caption_th: 'สี่เหลี่ยมสีขาวที่มีรู (เรืองแสง UV)',
  },
  {
    src: '/img/squareWithHole/white.jpg',
    model: 'squareWithHole',
    caption_en: 'White Square with a hole',
    caption_th: 'สี่เหลี่ยมสีขาวที่มีรู  ',
  },
  {
    src: '/img/squareWithHole/yellow.png',
    model: 'squareWithHole',
    caption_en: 'Yellow Square with a hole (UV Glow)',
    caption_th: 'สี่เหลี่ยมสีเหลืองที่มีรู (เรืองแสง UV)',
  },
  {
    src: '/img/squareWithHole/yellow.jpg',
    model: 'squareWithHole',
    caption_en: 'Yellow Square with a hole',
    caption_th: 'สี่เหลี่ยมสีเหลืองที่มีรู ',
  },
  {
    src: '/img/squareWithHole/yellowOrange.png',
    model: 'squareWithHole',
    caption_en: 'Yellow Orange Square with a hole (UV Glow)',
    caption_th: 'สี่เหลี่ยมสีเหลืองส้มที่มีรู (เรืองแสง UV)',
  },
  {
    src: '/img/squareWithHole/yellowOrange.jpg',
    model: 'squareWithHole',
    caption_en: 'Yellow Orange Square with a hole',
    caption_th: 'สี่เหลี่ยมสีเหลืองส้มที่มีรู  ',
  },

  {
    src: '/img/triangle/black.jpg',
    model: 'triangle',
    caption_en: 'Black Triangle',
    caption_th: 'สามเหลี่ยมดำ',
  },
  {
    src: '/img/triangle/blue.png',
    model: 'triangle',
    caption_en: 'Blue Triangle(UV Glow)',
    caption_th: 'สามเหลี่ยมสีน้ำเงิน (เรืองแสง UV))',
  },
  {
    src: '/img/triangle/blue.jpg',
    model: 'triangle',
    caption_en: 'Blue Triangle',
    caption_th: 'สามเหลี่ยมสีน้ำเงิน ',
  },
  {
    src: '/img/triangle/green.png',
    model: 'triangle',
    caption_en: 'Green Triangle(UV Glow)',
    caption_th: 'สามเหลี่ยมสีเขียว (เรืองแสง UV)',
  },
  {
    src: '/img/triangle/green.jpg',
    model: 'triangle',
    caption_en: 'Green Triangle',
    caption_th: 'สามเหลี่ยมสีเขียว ',
  },
  {
    src: '/img/triangle/magneta.png',
    model: 'triangle',
    caption_en: 'Magenta Triangle(UV Glow)',
    caption_th: 'สามเหลี่ยมสีม่วงแดง(เรืองแสงยูวี)',
  },
  {
    src: '/img/triangle/magneta.jpg',
    model: 'triangle',
    caption_en: 'Magenta Triangle',
    caption_th: 'สามเหลี่ยมสีม่วงแดง',
  },
  {
    src: '/img/triangle/orange.png',
    model: 'triangle',
    caption_en: 'Orange Triangle(UV Glow)',
    caption_th: 'สามเหลี่ยมสีส้ม (เรืองแสง UV)',
  },
  {
    src: '/img/triangle/orange.jpg',
    model: 'triangle',
    caption_en: 'Orange Triangle',
    caption_th: 'สามเหลี่ยมสีส้ม  ',
  },
  {
    src: '/img/triangle/pink.png',
    model: 'triangle',
    caption_en: 'Pink Triangle (UV Glow)',
    caption_th: 'สามเหลี่ยมสีชมพู (เรืองแสง UV)',
  },
  {
    src: '/img/triangle/pink.jpg',
    model: 'triangle',
    caption_en: 'Pink Triangle',
    caption_th: 'สามเหลี่ยมสีชมพู',
  },
  {
    src: '/img/triangle/red.png',
    model: 'triangle',
    caption_en: 'Red Triangle (UV Glow)',
    caption_th: 'สามเหลี่ยมแดง (เรืองแสง UV)',
  },
  {
    src: '/img/triangle/red.jpg',
    model: 'triangle',
    caption_en: 'Red Triangle',
    caption_th: 'สามเหลี่ยมแดง',
  },
  {
    src: '/img/triangle/violet.png',
    model: 'triangle',
    caption_en: 'Violet Triangle (UV Glow)',
    caption_th: 'สามเหลี่ยมสีม่วง (เรืองแสง UV)',
  },
  {
    src: '/img/triangle/violet.jpg',
    model: 'triangle',
    caption_en: 'Violet Triangle',
    caption_th: 'สามเหลี่ยมสีม่วง ',
  },
  {
    src: '/img/triangle/white.png',
    model: 'triangle',
    caption_en: 'White Triangle (UV Glow)',
    caption_th: 'สามเหลี่ยมสีขาว (เรืองแสง UV)',
  },
  {
    src: '/img/triangle/white.jpg',
    model: 'triangle',
    caption_en: 'White Triangle',
    caption_th: 'สามเหลี่ยมสีขาว  ',
  },
  {
    src: '/img/triangle/yellow.png',
    model: 'triangle',
    caption_en: 'Yellow Triangle (UV Glow)',
    caption_th: 'สามเหลี่ยมสีเหลือง (เรืองแสง UV)',
  },
  {
    src: '/img/triangle/yellow.jpg',
    model: 'triangle',
    caption_en: 'Yellow Triangle',
    caption_th: 'สามเหลี่ยมสีเหลือง ',
  },
  {
    src: '/img/triangle/yellowOrange.png',
    model: 'triangle',
    caption_en: 'Yellow Orange Triangle (UV Glow)',
    caption_th: 'สามเหลี่ยมสีส้มเหลือง (เรืองแสง UV)',
  },
  {
    src: '/img/triangle/yellowOrange.jpg',
    model: 'triangle',
    caption_en: 'Yellow Orange Triangle',
    caption_th: 'สามเหลี่ยมสีส้มเหลือง  ',
  },
];
apiRoute.get(async (req: NextApiRequest, res: NextApiResponse) => {
  const { model } = req.query;
  res.status(200).json({
    success: true,
    galleryImages:
      model == undefined
        ? galleryImages
        : galleryImages.filter((a) => a.model == model),
  });
});

export default apiRoute;
