import AccountBox from '@mui/icons-material/AccountBox';
import Dashboard from '@mui/icons-material/Dashboard';
import Apps from '@mui/icons-material/Apps';
import Public from '@mui/icons-material/Public';
import AttachMoney from '@mui/icons-material/AttachMoney';
import DataThresholding from '@mui/icons-material/DataThresholding';
import Apartment from '@mui/icons-material/Apartment';
import SouthAmerica from '@mui/icons-material/SouthAmerica';
import Badge from '@mui/icons-material/Badge';
import AccountTree from '@mui/icons-material/AccountTree';
import HotelIcon from '@mui/icons-material/Hotel';
import OpacityIcon from '@mui/icons-material/Opacity';
import InventoryIcon from '@mui/icons-material/Inventory';
import { RoutesType } from '@/interfaces/react.interface';

var dashRoutes: RoutesType[] = (module.exports = [
  {
    path: '/',
    name_en: 'Dashboard',
    name_fa: 'داشبورد',
    // @ts-ignore
    icon: Dashboard.type?.render().props.children.props.d,
    state: 'dashboardMain',
    componentName: 'MainDashboard',
    modelName: undefined,
  },
  {
    path: '',
    collapse: true,
    name_en: 'Users',
    name_fa: 'کاربران',
    // @ts-ignore
    icon: Badge.type?.render().props.children.props.d,
    state: 'userCollapse',
    componentName: undefined,
    modelName: undefined,
    views: [
      {
        path: '/users-page',
        name_en: 'Users List',
        name_fa: 'لیست کاربران',
        mini_en: 'UL',
        mini_fa: 'ل ک',
        state: 'usersList',
        componentName: 'Users',
        modelName: 'Users',
        predefineDb: false,
        activeOnly: false,
        editUrl: '/users-page/User',
        lookUps: ['agentsData'],
      },
      {
        path: '/users-page/user',
        name_en: 'Create user',
        name_fa: 'ایجاد کاربر ',
        mini_en: 'CU',
        mini_fa: 'ا ک',
        state: 'userSingle',
        componentName: 'User',
        modelName: 'Users',
        predefineDb: false,
        activeOnly: false,
      },
    ],
  },
  {
    path: '',
    collapse: true,
    name_en: 'Roles',
    name_fa: 'نقش ها',
    // @ts-ignore
    icon: AccountTree.type?.render().props.children.props.d,
    state: 'roleCollapse',
    componentName: undefined,
    modelName: undefined,
    views: [
      {
        path: '/rbacs-data',
        name_en: 'Roles List',
        name_fa: 'لیست نقش ها',
        mini_en: 'RL',
        mini_fa: 'ل ن',
        state: 'rolesList',
        componentName: 'Roles',
        modelName: 'Roles',
        predefineDb: false,
        activeOnly: false,
        editUrl: '/rbacs-data/Role',
        lookUps: ['userData'],
      },
      {
        path: '/rbacs-data/role',
        name_en: 'Create role',
        name_fa: 'ایجاد نقش ',
        mini_en: 'CR',
        mini_fa: 'ا ن',
        state: 'roleSingle',
        componentName: 'Role',
        modelName: 'Roles',
        predefineDb: false,
        activeOnly: false,
      },
    ],
  },
  {
    path: '/main-page-setup',
    collapse: true,
    name_en: 'Main page setup',
    name_fa: 'صفحه اصلی',
    // @ts-ignore
    icon: Apps.type?.render().props.children.props.d,
    state: 'mainPageCollapse',
    componentName: undefined,
    modelName: undefined,
    views: [
      {
        collapse: true,
        name_en: 'Collection banner',
        name_fa: 'بنر ویدیویی',
        mini_en: 'CB',
        mini_fa: 'ب و',
        state: 'collectionsCollapse',
        path: '/main-page-setup',
        componentName: undefined,
        modelName: undefined,
        predefineDb: false,
        activeOnly: false,
        views: [
          {
            path: '/main-page-setup/collections',
            name_en: 'Collections List',
            name_fa: 'فیلم های',
            mini_en: 'C',
            mini_fa: 'ف',
            state: 'collectionsList',
            componentName: 'Collections',
            modelName: 'Collections',
            predefineDb: false,
            activeOnly: false,
            editUrl: '/main-page-setup/collections/Collection',
          },
          {
            path: '/main-page-setup/collections/collection',
            name_en: 'Add collection',
            name_fa: 'فیلم',
            mini_en: 'C',
            mini_fa: 'ف',
            state: 'collectionSingle',
            componentName: 'Collection',
            modelName: 'Collections',
            predefineDb: false,
            activeOnly: false,
          },
        ],
      },
      // /myFirstDatabase
      // {
      //   collapse: true,
      //   name_en: 'Photo slider',
      //   name_fa: 'نوار عکس',
      //   mini_en: 'PS',
      //   mini_fa: 'ن ع',
      //   state: 'photosCollapse',
      //   componentName: undefined,
      //   modelName: undefined,
      //   predefineDb: false,
      //   activeOnly: false,
      //   views: [
      //     {
      //       path: '/main-page-setup/photos',
      //       name_en: 'Photos List',
      //       name_fa: 'عکس ها',
      //       mini_en: 'P',
      //       mini_fa: 'ع',
      //       state: 'photosList',
      //       componentName: 'Photos',
      //       modelName: 'Photos',
      //       predefineDb: false,
      //       activeOnly: false,
      //       editUrl: '/main-page-setup/photos/Photo',
      //     },
      //     {
      //       path: '/main-page-setup/photos/photo',
      //       name_en: 'Add Photo',
      //       name_fa: 'عکس',
      //       mini_en: 'P',
      //       mini_fa: 'ع',
      //       state: 'photoSingle',
      //       componentName: 'Photo',
      //       modelName: 'Photos',
      //       predefineDb: false,
      //       activeOnly: false,
      //     },
      //   ],
      // },
      // {
      //   collapse: true,
      //   name_en: 'Features slider',
      //   name_fa: 'امکانات',
      //   mini_en: 'FS',
      //   mini_fa: 'ا',
      //   state: 'featuresCollapse',
      //   path: '/main-page-setup',
      //   componentName: undefined,
      //   modelName: undefined,
      //   predefineDb: false,
      //   activeOnly: false,
      //   views: [
      //     {
      //       path: '/main-page-setup/features',
      //       name_en: 'Features List',
      //       name_fa: 'امکانات',
      //       mini_en: 'F',
      //       mini_fa: 'ا',
      //       state: 'featuresList',
      //       componentName: 'Features',
      //       modelName: 'Features',
      //       predefineDb: false,
      //       activeOnly: false,
      //       editUrl: '/main-page-setup/features/Feature',
      //     },
      //     {
      //       path: '/main-page-setup/features/feature',
      //       name_en: 'Add Feature',
      //       name_fa: 'ویژگی',
      //       mini_en: 'F',
      //       mini_fa: 'و',
      //       state: 'featureSingle',
      //       componentName: 'Feature',
      //       modelName: 'Features',
      //       predefineDb: false,
      //       activeOnly: false,
      //     },
      //   ],
      // },
      // {
      //   name_en: 'About us',
      //   name_fa: 'درباره',
      //   mini_en: 'AU',
      //   mini_fa: 'د',
      //   state: 'aboutSingle',
      //   path: '/main-page-setup/about',
      //   componentName: undefined,
      //   modelName: undefined,
      // },
    ],
  },
  {
    path: '/dashboard',
    collapse: true,
    name_en: 'Color Variety',
    name_fa: 'تنوع رنگ',
    // @ts-ignore
    icon: OpacityIcon.type?.render().props.children.props.d,
    state: 'colorCollapse',
    componentName: undefined,
    modelName: undefined,
    views: [
      {
        path: '/colors-data/colors',
        name_en: 'Colors List',
        name_fa: 'فهرست رنگ ها',
        mini_en: 'CL',
        mini_fa: 'ف ر',
        state: 'colorsList',
        componentName: 'Colors',
        modelName: 'Colors',
        predefineDb: false,
        activeOnly: false,
        editUrl: '/colors-data/colors/Color',
      },
      {
        path: '/colors-data/colors/Color',
        name_en: 'Add color',
        name_fa: 'رنگ اضافه کنید',
        mini_en: 'AC',
        mini_fa: 'را',
        state: 'colorSingle',
        componentName: 'Color',
        modelName: 'Colors',
        predefineDb: false,
        activeOnly: false,
      },
    ],
  },
  {
    path: '/dashboard',
    collapse: true,
    name_en: 'Products',
    name_fa: 'تنوع رنگ',
    // @ts-ignore
    icon: InventoryIcon.type?.render().props.children.props.d,
    state: 'productCollapse',
    componentName: undefined,
    modelName: undefined,
    views: [
      {
        path: '/products-data/products',
        name_en: 'Products List',
        name_fa: 'فهرست رنگ ها',
        mini_en: 'PL',
        mini_fa: 'ف ر',
        state: 'productsList',
        componentName: 'Products',
        modelName: 'Products',
        predefineDb: false,
        activeOnly: false,
        editUrl: '/products-data/products/Product',
      },
      {
        path: '/products-data/products/Product',
        name_en: 'Add product',
        name_fa: 'رنگ اضافه کنید',
        mini_en: 'AP',
        mini_fa: 'را',
        state: 'productSingle',
        componentName: 'Product',
        modelName: 'Products',
        predefineDb: false,
        activeOnly: false,
      },
    ],
  },
  // {
  //   path: '/dashboard',
  //   collapse: true,
  //   name_en: 'Main Data Activation',
  //   name_fa: 'فعال سازی داده های اصلی',
  //   // @ts-ignore
  //   icon: DataThresholding.type?.render().props.children.props.d,
  //   state: 'mainDataCollapse',
  //   componentName: undefined,
  //   modelName: undefined,
  //   views: [
  //     {
  //       collapse: true,
  //       name_en: 'All',
  //       name_fa: 'همه',
  //       mini_en: 'A',
  //       mini_fa: 'ه',
  //       state: 'globalCollapse',
  //       componentName: undefined,
  //       modelName: undefined,
  //       predefineDb: false,
  //       activeOnly: false,
  //       views: [
  //         {
  //           path: '/g-locations/g-countries',
  //           name_en: 'All countries',
  //           name_fa: 'همه کشورها',
  //           mini_en: 'AC',
  //           mini_fa: 'ه ک',
  //           state: 'globalCountries',
  //           componentName: 'Countries',
  //           modelName: 'Countries',
  //           predefineDb: true,
  //           activeOnly: false,
  //           editUrl: '/g-locations/g-countries/Countrie',
  //           lookUps: [
  //             'statesData',
  //             'citiesData',
  //             'userData',
  //             'agentsData',
  //             'suppliersData',
  //             'hotelsData',
  //           ],
  //           views: [
  //             {
  //               path: '/g-locations/g-countries/Countrie',
  //               name_en: 'Country',
  //               name_fa: 'ویژگی',
  //               mini_en: 'F',
  //               mini_fa: 'و',
  //               state: 'countrySingle',
  //               componentName: 'Country',
  //               modelName: 'Countries',
  //               predefineDb: true,
  //               activeOnly: false,
  //               editUrl: '/g-locations/g-countries/Countrie',
  //             },
  //           ],
  //         },
  //         {
  //           path: '/g-currencies/currencies',
  //           name_en: 'All currencies',
  //           name_fa: 'همه ارزها',
  //           mini_en: 'AC',
  //           mini_fa: 'ه ا',
  //           state: 'globalCurrencies',
  //           componentName: 'Currencies',
  //           modelName: 'Currencies',
  //           predefineDb: true,
  //           activeOnly: false,
  //           editUrl: '/g-currencies/currencies/Currencie',
  //           lookUps: ['agentsData', 'suppliersData'],
  //           views: [
  //             {
  //               path: '/g-currencies/currencies/Currencie',
  //               name_en: 'Currency',
  //               name_fa: 'ارز',
  //               mini_en: 'C',
  //               mini_fa: 'ا',
  //               state: 'currencySingle',
  //               componentName: 'Currency',
  //               modelName: 'Currencies',
  //               predefineDb: true,
  //               activeOnly: false,
  //               editUrl: '/g-currencies/currencies/Currencie',
  //             },
  //           ],
  //         },
  //         // {
  //         //   path: '/g-hotels/allhotels',
  //         //   name_en: 'All Hotels',
  //         //   name_fa: 'همه هتلها',
  //         //   mini_en: 'AH',
  //         //   mini_fa: 'ه ه',
  //         //   state: 'globalHotels',
  //         //   componentName: undefined,
  //         //   modelName: undefined,
  //         //   predefineDb: true,
  //         //   activeOnly: false,
  //         // },
  //       ],
  //     },
  //     {
  //       collapse: true,
  //       name_en: 'Only actives',
  //       name_fa: 'فقط فعال',
  //       mini_en: 'OA',
  //       mini_fa: 'ف',
  //       state: 'activeCollapse',
  //       componentName: undefined,
  //       modelName: undefined,
  //       views: [
  //         {
  //           path: '/a-locations/a-countries',
  //           name_en: 'Active countries',
  //           name_fa: 'کشورها فعال',
  //           mini_en: 'AC',
  //           mini_fa: 'ک',
  //           state: 'activeCountries',
  //           componentName: 'Countries',
  //           modelName: 'Countries',
  //           // @ts-ignore
  //           icon: Public.type?.render().props.children.props.d,
  //           predefineDb: true,
  //           activeOnly: true,
  //           editUrl: '/a-locations/a-countries/Countrie',
  //           lookUps: [
  //             'statesData',
  //             'citiesData',
  //             'userData',
  //             'agentsData',
  //             'suppliersData',
  //             'hotelsData',
  //           ],
  //           views: [
  //             {
  //               path: '/a-locations/a-countries/Countrie',
  //               name_en: 'Country',
  //               name_fa: 'ویژگی',
  //               mini_en: 'F',
  //               mini_fa: 'و',
  //               state: 'countrySingle',
  //               componentName: 'Country',
  //               modelName: 'Countries',
  //               predefineDb: true,
  //               activeOnly: true,
  //               editUrl: '/a-locations/a-countries/Countrie',
  //             },
  //           ],
  //         },
  //         {
  //           path: '/a-locations/provinces',
  //           name_en: 'Active provinces',
  //           name_fa: 'استان ها / ایالتهای فعال',
  //           mini_en: 'AP',
  //           mini_fa: ' ا',
  //           state: 'activeProvinces',
  //           componentName: 'Provinces',
  //           modelName: 'Provinces',
  //           // @ts-ignore
  //           icon: SouthAmerica.type?.render().props.children.props.d,
  //           predefineDb: true,
  //           activeOnly: true,
  //           editUrl: '/a-locations/provinces/Province',
  //           lookUps: [
  //             'citiesData',
  //             'userData',
  //             'agentsData',
  //             'suppliersData',
  //             'hotelsData',
  //           ],
  //           views: [
  //             {
  //               path: '/a-locations/provinces/Province',
  //               name_en: 'Province/State',
  //               name_fa: 'استان  / ایالت',
  //               mini_en: 'P',
  //               mini_fa: 'ا',
  //               state: 'provinceSingle',
  //               componentName: 'Province',
  //               modelName: 'Provinces',
  //               predefineDb: true,
  //               activeOnly: true,
  //               editUrl: '/a-locations/provinces/Province',
  //             },
  //           ],
  //         },
  //         {
  //           path: '/a-locations/cities',
  //           name_en: 'Active cities',
  //           name_fa: 'شهرها ی فعال',
  //           mini_en: 'AC',
  //           mini_fa: 'ش',
  //           state: 'activeCities',
  //           componentName: 'Cities',
  //           modelName: 'Cities',
  //           // @ts-ignore
  //           icon: Apartment.type?.render().props.children.props.d,
  //           predefineDb: true,
  //           activeOnly: true,
  //           editUrl: '/a-locations/cities/Citie',
  //           lookUps: ['userData', 'agentsData', 'suppliersData', 'hotelsData'],
  //           views: [
  //             {
  //               path: '/a-locations/cities/Citie',
  //               name_en: 'City',
  //               name_fa: 'شهر',
  //               mini_en: 'C',
  //               mini_fa: 'ش',
  //               state: 'citySingle',
  //               componentName: 'City',
  //               modelName: 'Cities',
  //               predefineDb: true,
  //               activeOnly: true,
  //               editUrl: '/a-locations/cities/Citie',
  //             },
  //           ],
  //         },
  //         {
  //           path: '/a-currencies/currencies',
  //           name_en: 'Active currencies',
  //           name_fa: 'ارزهای فعال',
  //           mini_en: 'AC',
  //           mini_fa: 'ک',
  //           state: 'activeCurrencies',
  //           componentName: 'Currencies',
  //           modelName: 'Currencies',
  //           // @ts-ignore
  //           icon: AttachMoney.type?.render().props.children.props.d,
  //           predefineDb: true,
  //           activeOnly: true,
  //           editUrl: '/a-currencies/currencies/Currencie',
  //           lookUps: ['agentsData', 'suppliersData'],
  //           views: [
  //             {
  //               path: '/a-currencies/currencies/Currencie',
  //               name_en: 'Currency',
  //               name_fa: 'ارز',
  //               mini_en: 'C',
  //               mini_fa: 'ا',
  //               state: 'currencySingle',
  //               componentName: 'Currency',
  //               modelName: 'Currencies',
  //               predefineDb: true,
  //               activeOnly: true,
  //               editUrl: '/a-currencies/currencies/Currencie',
  //             },
  //           ],
  //         },
  //         // {
  //         //   path: '/dashboard/a-hotels/hotels',
  //         //   'name_en': 'Active hotels',
  //         //   name_fa: 'هتلهای فعال',
  //         //   'mini_en': 'AH',
  //         //   mini_fa: 'ه',
  //         //   state: 'aHotelsMultiCollapse',
  //         ////   layout: '/admin',
  //         //   icon: HotelIcon.type?.render().props.children.props.d,
  //         // },
  //       ],
  //     },
  //   ],
  // },
  // {
  //   path: '/dashboard',
  //   collapse: true,
  //   name_en: 'Agency/Client Data',
  //   name_fa: 'اطلاعات آژانس/مشتری',
  //   // @ts-ignore
  //   icon: AccountBox.type?.render().props.children.props.d,
  //   state: 'agencyCollapse',
  //   componentName: undefined,
  //   modelName: undefined,
  //   views: [
  //     {
  //       path: '/agencies-data/agencies',
  //       name_en: 'Agencies List',
  //       name_fa: 'فهرست آژانس ها',
  //       mini_en: 'AL',
  //       mini_fa: 'ف آ',
  //       state: 'agenciesList',
  //       componentName: 'Agencies',
  //       modelName: 'Agencies',
  //       predefineDb: false,
  //       activeOnly: false,
  //       editUrl: '/agencies-data/agencies/Agencie',
  //     },
  //     {
  //       path: '/agencies-data/agencies/Agencie',
  //       name_en: 'Add agency',
  //       name_fa: 'آژانس اضافه کنید',
  //       mini_en: 'AA',
  //       mini_fa: 'آا',
  //       state: 'agencySingle',
  //       componentName: 'Agent',
  //       modelName: 'Agencies',
  //       predefineDb: false,
  //       activeOnly: false,
  //     },
  //   ],
  // },
  // {
  //   path: '/dashboard',
  //   collapse: true,
  //   name_en: 'Hotels Data',
  //   name_fa: 'اطلاعات هتلها',
  //   // @ts-ignore
  //   icon: HotelIcon.type?.render().props.children.props.d,
  //   state: 'hotelsCollapse',
  //   componentName: undefined,
  //   modelName: undefined,
  //   views: [
  //     {
  //       path: '/hotel-data/hotels',
  //       name_en: 'Hotels List',
  //       name_fa: 'فهرست هتلها',
  //       mini_en: 'HL',
  //       mini_fa: 'ف ه',
  //       state: 'hotelsList',
  //       componentName: undefined,
  //       modelName: undefined,
  //     },
  //     {
  //       path: '/hotel-data/hotels/hotel',
  //       name_en: 'Add hotel',
  //       name_fa: 'هتل اضافه کنید',
  //       mini_en: 'AH',
  //       mini_fa: 'آه',
  //       state: 'hotelSingle',
  //       componentName: undefined,
  //       modelName: undefined,
  //     },
  //   ],
  // },
]);

export default dashRoutes;
